name: Build Kotlin binding
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'commit/tag/branch reference'
        required: true
        type: string
  workflow_call:
    inputs:
      ref:
        description: 'commit/tag/branch reference'
        required: true
        type: string

jobs:
  build-kotlin-binding:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout breez-sdk repo
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref || github.sha }}
  
      - name: Install rust
        run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile minimal
  
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          version: "23.4"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Kotlin binding
        working-directory: libs/sdk-bindings
        run: |
          cargo run --features=uniffi/cli --bin uniffi-bindgen generate src/breez_sdk.udl --language kotlin -o ffi/kotlin
  
      - name: Archive Kotlin binding
        uses: actions/upload-artifact@v3
        with:
          name: breez_sdk.kt
          path: libs/sdk-bindings/ffi/kotlin/breez_sdk/breez_sdk.kt

      - name: Archive KMM bindings
        uses: actions/upload-artifact@v3
        with:
          name: kmm
          path: libs/sdk-bindings/ffi/kmm/*
