name: Build all platforms
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'commit/tag/branch reference'
        required: true
        type: string
  workflow_call:
    inputs:
      ref:
        description: 'commit/tag/branch reference'
        required: true
        type: string

jobs:
  build-windows:
    uses: ./.github/workflows/build-windows.yml
    with:
      ref: ${{ inputs.ref }}
  build-darwin:
    uses: ./.github/workflows/build-darwin.yml
    with:
      ref: ${{ inputs.ref }}
  build-linux:
    uses: ./.github/workflows/build-linux.yml
    with:
      ref: ${{ inputs.ref }}
