name: Publish Python Bindings
on:
  workflow_call:
    inputs:
      ref:
        description: 'commit/tag/branch reference'
        required: true
        type: string
      package-version:
        description: 'version for the python package (MAJOR.MINOR.BUILD)'
        required: true
        type: string
      publish:
        description: 'value indicating whether to publish to pypi.'
        required: true
        type: boolean
        default: false
    secrets:
      PYPI_API_TOKEN:
        description: 'api token to authenticate to pypi'
        required: true

jobs:
  build-macos-wheels:
    runs-on: macos-latest
    strategy:
      matrix:
        python:
          - "3.8"
          - "3.9"
          - "3.10"
    steps:
      - name: Checkout breez-sdk repo
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref || github.sha }}

      - name: "Install Python"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - uses: actions/download-artifact@v3
        with:
          name: sdk-bindings-darwin-universal
          path: libs/sdk-bindings/bindings-python/src/breez_sdk

      - uses: actions/download-artifact@v3
        with:
          name: bindings-python
          path: libs/sdk-bindings/bindings-python/src/breez_sdk

      - name: Clean up downloaded files
        run: |
          rm -f libs/sdk-bindings/bindings-python/src/breez_sdk/*.a
          ls -R libs/sdk-bindings/bindings-python

      - name: Update package version
        if: ${{ inputs.package-version }}
        working-directory: libs/sdk-bindings/bindings-python
        run: sed -i.bak -e 's/    version=".*",/    version="${{ inputs.package-version }}",/' setup.py

      - name: Install dependencies
        working-directory: libs/sdk-bindings/bindings-python
        run: pip3 install wheel setuptools

      - name: Build wheel
        working-directory: libs/sdk-bindings/bindings-python
        run: python3 setup.py bdist_wheel --plat-name macosx_11_0_universal2 --verbose

      - name: List wheel contents
        working-directory: libs/sdk-bindings/bindings-python/dist
        run: python3 -m zipfile --list *.whl || true

      - name: Archive the wheel
        uses: actions/upload-artifact@v3
        with:
          name: python-${{ matrix.python }}-macos-wheel
          path: libs/sdk-bindings/bindings-python/dist/*.whl

  publish-package:
    runs-on: ubuntu-latest
    needs: [build-macos-wheels]
    steps:
      - name: Checkout breez-sdk repo
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref || github.sha }}

      - name: Download wheels
        uses: actions/download-artifact@v3
        with:
          path: libs/sdk-bindings/bindings-python/dist/

      - name: Clean downloaded contents
        working-directory: libs/sdk-bindings/bindings-python
        run: |
          echo "Artifacts before cleaning"
          ls -laR dist
          find dist -maxdepth 1 ! -path dist ! -name "python*" -exec rm -rf {} \;
          echo "Artifacts after cleaning"
          ls -laR dist

      - name: "Publish on test PyPI"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          packages_dir: libs/sdk-bindings/bindings-python/dist/*/
