name: Publish all packages
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'commit/tag/branch reference'
        required: true
        type: string
      csharp-package-version:
        description: 'version for the C# nuget package (MAJOR.MINOR.BUILD)'
        required: false
        type: string
      csharp-ref:
        description: 'optional commit/tag/branch reference for the C# project. Defaults to ref.'
        required: false
        type: string
      golang-package-version:
        description: 'version for the golang package (MAJOR.MINOR.BUILD) (no v prefix)'
        required: false
        type: string
      maven-package-version:
        description: 'version for the android package (MAJOR.MINOR.BUILD)'
        required: false
        type: string
      kotlin-mpp-package-version:
        description: 'version for the kotlin multiplatform package (MAJOR.MINOR.BUILD)'
        required: false
        type: string

jobs:
  build-windows:
    uses: ./.github/workflows/build-windows.yml
    with:
      ref: ${{ inputs.ref || github.sha }}
  build-darwin:
    uses: ./.github/workflows/build-darwin.yml
    with:
      ref: ${{ inputs.ref || github.sha }}
  build-linux:
    uses: ./.github/workflows/build-linux.yml
    with:
      ref: ${{ inputs.ref || github.sha }}
  build-android:
    uses: ./.github/workflows/build-android.yml
    with:
      ref: ${{ inputs.ref || github.sha }}
  build-ios:
    uses: ./.github/workflows/build-ios.yml
    with:
      ref: ${{ inputs.ref || github.sha }}
  build-kotlin-binding:
    uses: ./.github/workflows/build-kotlin-binding.yml
    with:
      ref: ${{ inputs.ref || github.sha }}

  publish-csharp:
    needs: 
      - build-windows
      - build-darwin
      - build-linux
    if: ${{ inputs.csharp-package-version }}
    uses: ./.github/workflows/publish-csharp.yml
    with:
      ref: ${{ inputs.csharp-ref || inputs.ref || github.sha }}
      package-version: ${{ inputs.csharp-package-version || '0.0.2' }}
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

  publish-golang:
    needs: 
      - build-windows
      - build-darwin
      - build-linux
    if: ${{ inputs.golang-package-version }}
    uses: ./.github/workflows/publish-golang.yml
    with:
      ref: ${{ inputs.ref || github.sha }}
      package-version: ${{ inputs.golang-package-version || '0.0.2' }}
    secrets:
      REPO_SSH_KEY: ${{ secrets.REPO_SSH_KEY }}
  
  publish-android:
    needs: 
      - build-android
      - build-kotlin-binding
    if: ${{ inputs.maven-package-version }}
    uses: ./.github/workflows/publish-android.yml
    with:
      ref: ${{ inputs.ref || github.sha }}
      package-version: ${{ inputs.maven-package-version || '0.0.2' }}
    secrets:
      BREEZ_MVN_USERNAME: ${{ secrets.BREEZ_MVN_USERNAME }}
      BREEZ_MVN_PASSWORD: ${{ secrets.BREEZ_MVN_PASSWORD }}
  
  publish-kotlin-mpp:
    needs: 
      - build-android
      - build-ios
      - build-kotlin-binding
    if: ${{ inputs.kotlin-mpp-package-version }}
    uses: ./.github/workflows/publish-kotlin-mpp.yml
    with:
      ref: ${{ inputs.ref || github.sha }}
      package-version: ${{ inputs.kotlin-mpp-package-version || '0.0.2' }}
    secrets:
      BREEZ_MVN_USERNAME: ${{ secrets.BREEZ_MVN_USERNAME }}
      BREEZ_MVN_PASSWORD: ${{ secrets.BREEZ_MVN_PASSWORD }}
