name: Publish Android Bindings
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'commit/tag/branch reference'
        required: true
        type: string
      package-version:
        description: 'version for the gradle library (MAJOR.MINOR.BUILD)'
        required: true
        type: string
  workflow_call:
    inputs:
      ref:
        description: 'commit/tag/branch reference'
        required: true
        type: string
      package-version:
        description: 'version for the gradle library (MAJOR.MINOR.BUILD)'
        required: true
        type: string
    secrets:
      BREEZ_MVN_USERNAME:
        description: 'username for gradlew publish'
        required: true
      BREEZ_MVN_PASSWORD:
        description: 'password for gradlew publish'
        required: true

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout breez-sdk repo
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref || github.sha }}

      - uses: actions/download-artifact@v3
        with:
          name: sdk-bindings-aarch64-linux-android
          path: libs/sdk-bindings/bindings-android/lib/src/main/arm64-v8a
      
      - uses: actions/download-artifact@v3
        with:
          name: sdk-bindings-armv7-linux-androideabi
          path: libs/sdk-bindings/bindings-android/lib/src/main/armeabi-v7a

      - uses: actions/download-artifact@v3
        with:
          name: sdk-bindings-i686-linux-android
          path: libs/sdk-bindings/bindings-android/lib/src/main/x86

      - uses: actions/download-artifact@v3
        with:
          name: sdk-bindings-x86_64-linux-android
          path: libs/sdk-bindings/bindings-android/lib/src/main/x86_64

      - uses: actions/download-artifact@v3
        with:
          name: breez_sdk.kt
          path: libs/sdk-bindings/bindings-android/lib/src/main/kotlin

      - name: Build Android project
        working-directory: libs/sdk-bindings/bindings-android
        env:
          ORG_GRADLE_PROJECT_libraryVersion: ${{ inputs.package-version || '0.0.1' }}
        run: ./gradlew assemble

      - name: Archive aar
        uses: actions/upload-artifact@v3
        with:
          name: android-release.aar
          path: libs/sdk-bindings/bindings-android/lib/build/outputs/aar/lib-release.aar
        
      - name: Publish artifacts
        if: ${{ inputs.package-version }}
        working-directory: libs/sdk-bindings/bindings-android
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BREEZ_MVN_USERNAME: ${{ secrets.BREEZ_MVN_USERNAME }}
          BREEZ_MVN_PASSWORD: ${{ secrets.BREEZ_MVN_PASSWORD }}
        run: |
          ./gradlew publish -PlibraryVersion=${{ inputs.package-version }} -PbreezReposiliteUsername="$BREEZ_MVN_USERNAME" -PbreezReposilitePassword="$BREEZ_MVN_PASSWORD"
